=== xcomart/libcmdbm/data/cmdbm_config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    The XML form of a libcmdbm configuration.

    A DTD cannot express that the tag name of a datasource is its DBMS type:
    any key registered with CMDBM_RegisterDBMS may be spelled as a tag under
    <Databases>, so a configuration which uses a custom module will not
    validate against this DTD. The built-in types are listed below.

    Everywhere a setting may be written either as an attribute or as a child
    tag, the child tag wins.
-->

<!ELEMENT Configuration (Databases, Logging?, PoolConfigurations?)>

<!ELEMENT Databases ((ODBC|Oracle|MySQL|SQLite|PgSql|Custom)+)>

<!-- settings shared by the datasource types -->
<!ELEMENT DSN (#PCDATA)>
<!ELEMENT TNSName (#PCDATA)>
<!ELEMENT Host (#PCDATA)>
<!ELEMENT Port (#PCDATA)>
<!ELEMENT Database (#PCDATA)>
<!ELEMENT User (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT File (#PCDATA)>

<!-- a connection parameter passed to the module as is.
     the value is the 'value' attribute, or the text content when there is
     no such attribute. -->
<!ELEMENT Param (#PCDATA)>
<!ATTLIST Param
    key CDATA #REQUIRED
    value CDATA #IMPLIED>

<!-- the connection pool of a datasource. 'confRef' names a <PoolConfig>
     whose settings are the starting point, the ones given here override
     it. -->
<!ELEMENT Pool (PingInterval?, PingTest?, TestOnBorrow?,
                InitCount?, MaxCount?, TestSql?)>
<!ATTLIST Pool
    confRef IDREF #IMPLIED
    pingInterval CDATA #IMPLIED
    pingTest (true|false) #IMPLIED
    testOnBorrow (true|false) #IMPLIED
    initCount CDATA #IMPLIED
    maxCount CDATA #IMPLIED
    testSql CDATA #IMPLIED>
<!ELEMENT PingInterval (#PCDATA)>
<!ELEMENT PingTest (#PCDATA)>
<!ELEMENT TestOnBorrow (#PCDATA)>
<!ELEMENT InitCount (#PCDATA)>
<!ELEMENT MaxCount (#PCDATA)>
<!ELEMENT TestSql (#PCDATA)>

<!-- the mapper files of a datasource. 'monitorInterval' is how many seconds
     pass between two rescans, 30 without it. -->
<!ELEMENT Mappers ((Mapper|MapperSet)+)>
<!ATTLIST Mappers monitorInterval CDATA #IMPLIED>
<!-- one mapper file: the 'file' attribute, or the text content. -->
<!ELEMENT Mapper (#PCDATA)>
<!ATTLIST Mapper file CDATA #IMPLIED>
<!-- every mapper file of a directory which matches the pattern. -->
<!ELEMENT MapperSet (#PCDATA)>
<!ATTLIST MapperSet
    basePath CDATA #REQUIRED
    filePattern CDATA #REQUIRED
    recursive (true|false) #IMPLIED>

<!ELEMENT ODBC (DSN?, Database?, User?, Password?, Param*, Pool?, Mappers?)>
<!ATTLIST ODBC
    id ID #REQUIRED
    charset CDATA #IMPLIED
    dsn CDATA #IMPLIED
    database CDATA #IMPLIED
    user CDATA #IMPLIED
    password CDATA #IMPLIED>

<!ELEMENT Oracle (TNSName?, Database?, User?, Password?,
                  Param*, Pool?, Mappers?)>
<!ATTLIST Oracle
    id ID #REQUIRED
    charset CDATA #IMPLIED
    tnsName CDATA #IMPLIED
    database CDATA #IMPLIED
    user CDATA #IMPLIED
    password CDATA #IMPLIED>

<!ELEMENT MySQL (Host?, Port?, Database?, User?, Password?,
                 Param*, Pool?, Mappers?)>
<!ATTLIST MySQL
    id ID #REQUIRED
    charset CDATA #IMPLIED
    host CDATA #IMPLIED
    port CDATA #IMPLIED
    database CDATA #IMPLIED
    user CDATA #IMPLIED
    password CDATA #IMPLIED>

<!ELEMENT SQLite (File?, Param*, Pool?, Mappers?)>
<!ATTLIST SQLite
    id ID #REQUIRED
    charset CDATA #IMPLIED
    file CDATA #IMPLIED
    serialize (true|false) #IMPLIED>

<!ELEMENT PgSql (Host?, Port?, Database?, User?, Password?,
                 Param*, Pool?, Mappers?)>
<!ATTLIST PgSql
    id ID #REQUIRED
    charset CDATA #IMPLIED
    host CDATA #IMPLIED
    port CDATA #IMPLIED
    database CDATA #IMPLIED
    user CDATA #IMPLIED
    password CDATA #IMPLIED>

<!ELEMENT Custom (Param*, Pool?, Mappers?)>
<!ATTLIST Custom
    id ID #REQUIRED
    charset CDATA #IMPLIED
    soPath CDATA #IMPLIED>

<!-- pool settings a <Pool confRef="..."> can start from. -->
<!ELEMENT PoolConfigurations (PoolConfig+)>
<!ELEMENT PoolConfig (PingInterval?, PingTest?, TestOnBorrow?,
                      InitCount?, MaxCount?, TestSql?)>
<!ATTLIST PoolConfig
    id ID #REQUIRED
    pingInterval CDATA #IMPLIED
    pingTest (true|false) #IMPLIED
    testOnBorrow (true|false) #IMPLIED
    initCount CDATA #IMPLIED
    maxCount CDATA #IMPLIED
    testSql CDATA #IMPLIED>

<!-- what a session writes to the log. the value is the 'show' attribute, or
     the text content when there is no such attribute. -->
<!ELEMENT Logging (QueryId?, Query?, Result?)>
<!ELEMENT QueryId (#PCDATA)>
<!ATTLIST QueryId show (true|false) #IMPLIED>
<!ELEMENT Query (#PCDATA)>
<!ATTLIST Query show (true|false) #IMPLIED>
<!ELEMENT Result (#PCDATA)>
<!ATTLIST Result show (true|false) #IMPLIED>

=== xcomart/libcmdbm/data/cmdbm_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configuration SYSTEM "cmdbm_config.dtd">
<!-- the XML form of data/cmdbm_config.json. either form may be handed to
     CMDBM_ContextCreate, the format is decided by the content. -->
<Configuration>
    <Databases>
        <ODBC id="odbcName" charset="utf-8">
            <DSN></DSN>
            <User></User>
            <Password></Password>
            <Pool confRef="basePoolConfig" />
            <Mappers>
                <MapperSet basePath="" filePattern="" />
            </Mappers>
        </ODBC>
        <Oracle id="oracleName" charset="utf-8">
            <TNSName></TNSName>
            <User></User>
            <Password></Password>
            <Pool confRef="basePoolConfig">
                <TestSql>select 1 from dual</TestSql>
            </Pool>
            <Mappers>
                <MapperSet basePath="" filePattern="" />
            </Mappers>
        </Oracle>
        <MySQL id="mysqlName" charset="utf-8">
            <Host></Host>
            <Port>3306</Port>
            <Database></Database>
            <User></User>
            <Password></Password>
            <Pool confRef="basePoolConfig" />
            <Mappers>
                <MapperSet basePath="" filePattern="" />
            </Mappers>
        </MySQL>
        <SQLite id="sqliteName">
            <File></File>
            <Pool confRef="basePoolConfig" />
            <Mappers>
                <MapperSet basePath="" filePattern="" />
            </Mappers>
        </SQLite>
        <PgSql id="pgsqlName" charset="utf-8">
            <Host></Host>
            <Port>5432</Port>
            <Database></Database>
            <User></User>
            <Password></Password>
            <Param key="param1" value="" />
            <Pool confRef="basePoolConfig" />
            <Mappers monitorInterval="30">
                <MapperSet basePath="" filePattern="" recursive="false" />
            </Mappers>
        </PgSql>
        <Custom id="custName" charset="utf-8">
            <Param key="param1">value1</Param>
        </Custom>
    </Databases>
    <Logging>
        <QueryId show="true" />
        <Query show="true" />
        <Result show="false" />
    </Logging>
    <PoolConfigurations>
        <PoolConfig id="basePoolConfig" pingInterval="30"
                pingTest="true" testOnBorrow="true">
            <InitCount>5</InitCount>
            <MaxCount>100</MaxCount>
            <TestSql>select 1</TestSql>
        </PoolConfig>
    </PoolConfigurations>
</Configuration>
